{% set version = "0.6.2" %}
{% set name = "pyrosm" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 904e9636e71fd558d127807a0beb9b53e4d2e28a2301d3c46ed8ba2d84d5e1b9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python >=3.9
    - pip
    - cython >=0.28
    - pyrobuf >=0.9.3
    - shapely >=2.0
    - geopandas >=0.12.0
    - cykhash >=2.0
    - python-rapidjson
  run:
    - python >=3.9
    - shapely >=2.0
    - pyrobuf >=0.9.3
    - geopandas >=0.12.0
    - cykhash >=2.0
    - python-rapidjson

test:
  imports:
    - pyrosm

about:
  home: https://github.com/HTenkanen/pyrosm
  license: MIT
  license_file: LICENSE
  summary: A Python tool to parse OSM data from Protobuf format into Geopandas GeoDataFrames.

extra:
  recipe-maintainers:
    - htenkanen
