{% set version = "0.7.0" %}
{% set name = "pyrosm" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a2dcb46c44b1d1ca9de8e62bd8a5159f42d80f63ccf4a7ee67ae9c16a2c59b52

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cykhash >=2.0
    - cython >=0.28
    - geopandas >=0.12.0
    - pyrobuf >=0.9.3
    - python-rapidjson
    - shapely >=2.0
  run:
    - python
    - cykhash >=2.0
    - cython >=0.28
    - geopandas >=0.12.0
    - pyrobuf >=0.9.3
    - python-rapidjson
    - shapely >=2.0

test:
  imports:
    - pyrosm

about:
  home: https://github.com/pyrosm/pyrosm
  license: MIT
  license_file: LICENSE
  summary: A Python tool to parse OSM data from Protobuf format into Geopandas GeoDataFrames.

extra:
  recipe-maintainers:
    - htenkanen
