{% set version = "0.8.0" %}
{% set name = "pyrosm" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0774b5e853be74e4e292eb0073f321ccd42658e622c317af2f31e164e4969fb7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=18.0
    - wheel
    - cython
    - cykhash >=2
    - certifi
    - geopandas >=0.12.0
    - protobuf >=6.33.5
    - python-rapidjson
    - shapely >=2.1
  run:
    - python
    - setuptools >=18.0
    - cykhash >=2
    - certifi
    - geopandas >=0.12.0
    - protobuf >=6.33.5
    - python-rapidjson
    - shapely >=2.1

test:
  imports:
    - pyrosm

about:
  home: https://github.com/pyrosm/pyrosm
  license: MIT
  license_file: LICENSE
  summary: A Python tool to parse OSM data from Protobuf format into Geopandas GeoDataFrames.

extra:
  recipe-maintainers:
    - htenkanen
