{% set version = "0.5.3" %}
{% set name = "pyrosm" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: afd6f1431f77e7a4a5e4c99cc7c585ae77db18e5ffac33ce868d18e7e940f31c

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.28
    - pyrobuf >=0.9.3
    - pygeos
    - shapely
    - geopandas
    - cykhash
    - python-rapidjson
  run:
    - python
    - shapely
    - pyrobuf >=0.9.3
    - geopandas
    - pygeos
    - cykhash
    - python-rapidjson

test:
  imports:
    - pyrosm

about:
  home: https://github.com/HTenkanen/pyrosm
  license: MIT
  license_file: LICENSE
  summary: A Python tool to parse OSM data from Protobuf format into Geopandas GeoDataFrames.

extra:
  recipe-maintainers:
    - htenkanen
