{% set version = "0.6.0" %}
{% set name = "pyrosm" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d7270a3cd4ff6ee9c1f7c309fb0a7df0e3b28a6a6ffd7978c94a9b3db162e62e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.28
    - pyrobuf >=0.9.3
    - pygeos
    - shapely
    - geopandas >= 0.8.0
    - cykhash
    - python-rapidjson
  run:
    - python
    - shapely
    - pyrobuf >=0.9.3
    - geopandas >= 0.8.0
    - pygeos
    - cykhash
    - python-rapidjson

test:
  imports:
    - pyrosm

about:
  home: https://github.com/HTenkanen/pyrosm
  license: MIT
  license_file: LICENSE
  summary: A Python tool to parse OSM data from Protobuf format into Geopandas GeoDataFrames.

extra:
  recipe-maintainers:
    - htenkanen
